# Generated by Django 3.1 on 2022-12-03 08:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20221201_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
