# Generated by Django 4.1.6 on 2023-02-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20221203_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='text',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
